version: "3.8"
services:
  database:
    image: "mongo"
  express:
    build: ./MyApp-Backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - database
  angular:
    build: ./MyApp-Frontend
    ports:
      - "4300:80"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - express
      - angular     